modLoader="javafml"
loaderVersion="[43,)"
license="Apache-2.0 License"
issueTrackerURL="https://github.com/MaxSaleh/Market-Crates-Legacy/issues"

[[mods]]
   modId="marketcrates"
   version="1.4.2"
   displayName="Market Crates"

updateJSONURL=""
displayURL="https://github.com/MaxSaleh/Market-Crates-Legacy"
logoFile="marketcrates_logo.png"
authors="MaxIsH0t"

description='''
Some crates to spice up your towns, markets, fishing docs, you name it!
- Available in all different wood types
- Shows their inventory contents
- You can stack them
- You can put a stick under it to give the crate in incline
Shift click the crate to place stack crates in the same block space.
Hit the crate with a stick to incline the crate. Hit it once with an axe to retrieve the stick (For creative mode right clicking with a stick toggles it)
'''

[[dependencies.marketcrates]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.marketcrates]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"